import './index.css'


export function DoctorPP () {
    return (
       <div className="flex-tos">
        <div>
            <h2>Doctors Privacy policies</h2>
            <h3>Terms and Conditions</h3>
            <p>Thank you for using Veri Doctor&apos;s Services. These Terms and Conditions (the “Terms”) are a legally binding agreement made by and between Veri Doctor, (“Veri Doctor” and/ or “us”), and you, acting in your capacity as an individual and, if applicable, on behalf of the entity, you are legally representing or for whom you are using this application (collectively, “Provider”, “you”, “your”, “yours”).</p>
            <p>All reference to the Terms encompasses any terms, guidelines, and rules approved/provided by Veri Doctor.</p>
            <p>You understand that by using these Services you acknowledge and agree that Veri Doctor will treat your use of the Services as an acceptance of the Terms and to be fully bound thereby.</p>
            <p>These Terms govern your access to and use of www.veridoctor.com in addition to any other website owned, operated, licensed, or controlled by Veri Doctor (collectively, the “Site”) and the products, services or applications (the “Application”) offered or developed by Veri Doctor (collectively the “Services”). Further, these terms, as amended from time to time, govern your use of any online Services that may be provided by Veri Doctor to which you have access, as well as any Service that requires an Internet connection or Veri Doctor&apos;s Origin account to access or install, as well as any other account you use to access online products or Services offered by Veri Doctor.</p>
            <ol className='main-list-items'>
                <li><b>Our Services</b>
                    <ol className='sub-list-items'>
                        <li>Our Services constitute a technology platform that allows users of Veri Doctor&apos;s Application or Site to search and book appointments with you as an independent healthcare provider. Providers subscribed to our platform include clinics, hospitals, medical professionals, laboratories, and other health services. In other words, we permit users to easily access Providers, such as yourself, to receive medical treatment.</li>
                        <li>IT IS CRUCIAL TO UNDERSTAND THAT YOU ARE WHOLLY AND SOLELY RESPONSIBLE FOR PROVIDING USERS WITH THE BEST MEDICAL ADVICE TREATMENT SUITED TO THEIR MEDICAL NEEDS THEY NEED AND FOR OFFERING AND PRESENTING THEM WITH THE CORRECT, ACCURATE, AND EFFICIENT TREATMENT THEY SEEK FROM YOU. WE DO NOT -AND DO NOT INTEND TO- PRACTICE MEDICINE. WE ONLY HELP CONNECT YOU TO USERS SEEKING HEALTHCARE CONSULTATION AND TREATMENT.</li>
                        <li>The Services are not intended for use by you if you, or the entity you are an affiliate thereto, or the entity you are the representative thereof, are/is legally unauthorized to practice your/its profession or conduct your/its activities. By agreeing to these Terms, you represent and warrant to Veri Doctor that you and your entity are/is legally licensed to conduct your/its professional activities.</li>
                        <li>You agree that materials available through our Services are for informational purposes or for facilitating the user&apos;s activities only, and do not act as a substitute for professional medical advice. The information and Services on this Website are provided only for activities related to medical professions and are not intended to be directly presented to patients. Veri Doctor, its licensors, and its suppliers are not responsible for any breaches or disclosures of content from this Website to any third parties including but not limited to patients.</li>
                    </ol>
                </li>
                <b><li>License</li></b>
                    <ol className="sub-list-items">
                        <li>By using our Services, we hereby grant you a limited, revocable, non-exclusive, non-sublicensable, right to (i) access, upload, and use our mobile application or website for the sole purpose of using our Services; and (ii) access and use information and materials provided, made available or otherwise found on our Content.</li>
                        <li>This license is not intended to be sub-assigned, sold, rented, leased, exported, imported, distributed, transferred, or otherwise granted to third parties, nor is such license intended for commercial use. You are only licensed to use our Services for personal, non-lucrative, noncommercial use.</li>
                        <li>You are prohibited from probing, scanning, or testing the vulnerability of any system or network breach or otherwise circumventing any security or authentication measures, accessing, tampering with, or using non-public areas of the Service, or shared areas of the Service you have not been invited to, Veri Doctor&apos;s or Veri Doctor&apos;s service providers&apos; computer systems; interfering with or disrupting any user, host, or network, for example by sending a virus, overloading, flooding, spamming, or mail-bombing any part of the Services; planting malware or otherwise using the Services to distribute malware, access or search the Services by any means other than our publicly supported interfaces (for example, “scraping”), sending unsolicited communications, promotions, advertisements, or spam, sending altered, deceptive or false sourcing information, including “spoofing” or “phishing”, publish anything that is fraudulent, misleading, or infringes others’ rights, promote or advertise products or services other than your own without appropriate authorization; impersonate or misrepresent your affiliation with any person or entity; publish or share materials that are unlawfully pornographic, indecent, or advocating bigotry, religious, racial or ethnic hatred, violating the law in any way, the privacy of others, or to defame others.</li>
                    </ol>
                <b><li>Restrictions</li></b>
                    <ol className='sub-list-items'>
                        <li>Providers shall not probe, scan, or test the vulnerability of any system or network breach or otherwise circumvent any security or authentication measures, access, tamper with, or use non-public or non-shared areas of the Services; interfere with or disrupt any host or network, overload, flood, spam, or mail-bomb any part of the Services; plant malware or otherwise use the Services to distribute malware, access or search the Services by any means other than our publicly supported interfaces, send unsolicited communications, promotions, advertisements, plant deceptive or false sourcing information, including “spoofing” or “phishing”, publish anything fraudulent, misleading, or infringes others’ rights, promote or advertise products or services other than their own; share unlawful, indecent or defamatory material, or share content advocating bigotry, religious, racial or ethnic hatred.</li>
                        <li>Subject to these Terms, you are hereby granted a limited, revocable, non-exclusive right to use the content and materials on the application in the normal course of use of the application. You may not use any third-party intellectual property without the express written permission of the applicable third party, except as permitted by law.</li>
                    </ol>
                <b><li>Provider Registration and Passwords</li></b>
                    <ol className='sub-list-items'>
                        <li>To access the Provider features of the Services, you will need to register with Veri Doctor and create an account through the online registration process on the Website. Your account gives you access to the Services and functionality that we may establish and maintain from time to time and at our sole discretion. In creating an account, you must provide Veri Doctor with accurate and complete registration information, as prompted in the registration form. You must promptly notify Veri Doctor if any of this information changes. If you fail to provide or update this information, Veri Doctor may, in its sole discretion, terminate your right to use the application or the Services.</li>
                        <li>In case this is your first approach to Veri Doctor, and you have duly inserted your informational data, you are kindly requested to contact Veri Doctor to open an account for your practice. To use our Services, you will have to sign a (“Provider’s Agreement”) in which you commit to legally adhere to the Terms and to download our mobile application. Additionally, you have to submit the permits, certificates, and licenses proving you are duly authorized to practice medicine, as well as your personal information (together with your “Folder”) to Veri Doctor. You hereby grant Veri Doctor the exclusive, transferable, sub-licensable, royalty-free, perpetual, irrevocable license to use, reproduce, publish, translate, sublicense, copy, modify, delete, enhance, and distribute your Folder and to incorporate same on our platform.</li>
                        <li>When you open your account, you will be asked to choose a password. You must keep your password confidential and under no circumstances should you respond to a request for your password, particularly when it is from an individual claiming to be an employee of Veri Doctor. Veri Doctor’s employees will never ask for your password. You must notify Veri Doctor if you receive such a request.</li>
                        <li>You will be responsible for all use of your password and account, including, without limitation, any use by any unauthorized third party. You must notify Veri Doctor immediately if you believe your password or account has been obtained or may be accessed or used by any unauthorized person or entity. In addition, you must notify Veri Doctor immediately if you become aware of any other breach or attempted breach of the security of the application.</li>
                        <li>You are responsible for any activity using your account, whether or not you authorized that activity. You acknowledge that if you wish to protect your transmission of data or files to Veri Doctor, it is your responsibility to use a secured encrypted connection to access and use the Services. Three consecutive logon failures will result in the suspension of your login information requiring you to contact Veri Doctor via email to revalidate your account.</li>
                        <li>We have implemented commercially reasonable technical and organizational measures designed to secure your personal information from accidental loss and unauthorized access, use, alteration, or disclosure. However, we cannot guarantee that unauthorized third parties will be unable to defeat those measures or use your personal information for improper purposes. You acknowledge that you provide your personal information at your own risk.</li>
                        <li>You must take into consideration that:
                            <ul>
                                <li>Your data, permits, and licenses must be accurate, complete, and updated at all times. Failing to do so, you acknowledge that Veri Doctor has the right to terminate your use of the Services.</li>
                                <li>You must choose a password to access your User Account and must keep it confidential at all times.</li>
                                <li>You understand that you will be responsible for any actions/activities made on your Provider account by unauthorized third parties. You must notify us if you strongly believe your account has been hacked.</li>
                                <li>Under no circumstances should you respond to a request for your password, particularly a request from someone claiming to be an employee of Veri Doctor.</li>
                                <li>You shall not authorize, assign, or transfer your Provider account to third parties.</li>
                                <li>You understand that you will be denied access to your account if you fail to enter your password for 2 consecutive times.</li>
                            </ul>
                        </li>
                    </ol>
                    <li><b>Consent to Communications from Veri Doctor</b></li>
                    <p>By registering as a Provider and providing Veri Doctor your email address, you consent to our using the email address to send you Service-related notices, including any notices required by law, changes in features, and special offers instead of communication by postal mail. You may opt out of such Service-related emails by opting out of such a feature.</p>
                <b><li>Third Party Sites</li></b>
                    <p>The application may contain links to third-party websites, advertisers, or services that are not owned or controlled by Veri Doctor. Veri Doctor has no control over and assumes no responsibility for, the content, privacy policies, or practices of any third-party websites or services, and Veri Doctor’s Privacy Policy does not apply to your use of such sites. If you access a third-party website from Veri Doctor’s Website, you do so at your own risk. You expressly release Veri Doctor from any liability arising out of your use of any third-party websites or services or third-party-owned content. Additionally, your dealings with or participation in promotions of advertisers found on the Website, including payment and delivery of goods, and any other terms (such as warranties) are solely between you and such advertisers. You agree that Veri Doctor shall not be responsible for any loss or damage of any sort relating to your dealings with such advertisers.</p>
                <b><li>Provider&apos;s Created Content</li></b>
                    <ol className='sub-list-items'>
                        <li>By using our Services, you provide us with information, files, and folders that you submit to Veri Doctor (together, “your folder”). By posting, storing or transmitting any content on or to the application, including by submitting Provider Created Content within the Website, you accept to grant Veri Doctor or represent and warrant that the owner of such content has expressly granted Veri Doctor, the exclusive, transferable, sub-licensable, royalty-free, perpetual, irrevocable, right and license to use, reproduce, publish, translate, sublicense, copy, modify, delete, enhance and distribute such content to incorporate same on Veri Doctor’s platform including but not limited to Veri Doctor’s Website. This incorporation includes the act of processing such content including but not limited to products, features, image thumbnails or document previews, design choices we make to technically administer our Services, for example, how we redundantly backup data to keep it safe. You give us the permissions we need to do all of the above for the sole and exclusive purpose of providing and promoting the Services. This permission also extends to trusted third parties.</li>
                        <li>You acknowledge that the usage of the content by Veri Doctor on Veri Doctor&apos;s platform will not constitute any infringement of the intellectual property, copyrights, or trademarks owned by you. Veri Doctor acknowledges to collect your prior approval to disclose any content on any platforms other than Veri Doctor. The refusal by the user to approve such disclosure will preclude Veri Doctor from same. You retain full ownership of your folder or the format that will be created by Veri Doctor as the Provider Created Content.</li>
                        <li>You understand and agree that the relationship established by and between you and Veri Doctor is a management agreement to gather, acquire, collect, transfer, process, merge, and migrate data and that you have provided it to Veri Doctor for this purpose. Aside from the rare exceptions we identify in our Privacy Policy, no matter how the Services change, we won’t share your content with the law enforcement authorities, for any purpose unless you direct us to. You are solely responsible for the accuracy, completeness, appropriateness, and legality of files, posts, or any other information you provide to Veri Doctor. The Services provide features that allow you to share your content with others working under your supervision, which allows them to access that content folder and can copy, modify, or even share the content, so you are advised to be careful with the content you are sharing with your employees. You hereby agree and acknowledge that Veri Doctor will retain your profile on Veri Doctor&apos;s platform even after you no longer access or use Veri Doctor&apos;s Services.</li>
                    </ol>
                <b><li>Veri Doctor&apos;s Created Content</li></b>
                    <ol className='sub-list-items'>
                        <li>Veri Doctor’s created content encompasses all the available material on the application through the Services, including without limitation, the logos, design, text, and graphics, as well as the selection, arrangement, and organization thereof. It also includes the names, logos, designs, and titles of Veri Doctor’s products.</li>
                        <li>Moreover, Veri Doctor’s created content covers all page headers, custom graphics, button icons, scripts, trademarks, or trade dress of Veri Doctor. If you use such content, you must include appropriate attribution. All other trademarks, trade names, and the like that appear on the application are the property of their respective owners. You shall not use any of these trademarks, trade dress, trade names, or any confusingly similar marks, dress, or names, without prior express written approval by Veri Doctor or the proprietorship thereof.</li>
                        <li>You may choose to or we may invite you to submit comments, testimonials, feedback, suggestions, ideas, and other submissions about the Services, including without limitation about how to improve the Services or our products (“Ideas”). By submitting any Idea, you acknowledge that your disclosure is gratuitous and unsolicited and that will not place Veri Doctor under any fiduciary or other obligation related thereto, that Veri Doctor is free to disclose the Ideas on a non-confidential basis to anyone or otherwise use the Ideas without any additional compensation to you. Such disclosure, submission, or offer of any Ideas shall, and hereby does, constitute towards Veri Doctor a perpetual, royalty-free, worldwide, and irrevocable license, title, and interest in all patent, copyright, trademark, and all other intellectual property and other rights whatsoever in and to the Ideas and a waiver of any claim based on moral rights, unfair competition, and any other legal base. You should not submit any Ideas to us if you do not wish to license such rights to us. You are and shall remain solely responsible for the content of any Ideas you make.</li>
                    </ol>
                <b><li>Your Responsibilities</li></b>
                    <ol className='sub-list-items'>
                        <li>The other content in the Services may be protected by the intellectual property rights of others and is deemed confidential. Please do not copy, upload, download, or share those files. You, will be fully and solely responsible and liable for what you copy, share, upload, download or otherwise use while using the Services.</li>
                        <li>You will be fully and solely responsible for maintaining, safeguarding, and protecting all your data. Veri Doctor will not be liable for any loss or corruption of your data, any costs or expenses associated with backing-up or restoring any of your data, or to compensate any damages incurred to you due to the lack of protection to such data.</li>
                        <li>You will not use the Services to establish, attempt to establish, or enforce, directly or indirectly, any agreement or coordination of the prices, frequencies, or amounts of any product or Service charged by Veri Doctor, or otherwise engage or attempt to engage in price fixing, output restriction, or customer or market allocation. You will not use the Services, directly or indirectly, to engage in any anti-competitive, deceptive, or unfair practices, or otherwise violate applicable antitrust, competition, or consumer protection laws, or regulations.</li>
                        <li>Veri Doctor provides accessible Services on different equipment and devices including but not limited to, certain mobile devices, and computers, which you will provide. Veri Doctor is not liable to provide the required devices or the telecommunication facilities i.e. internet connection or mobile service.</li>
                    </ol>
                <b><li>Refunds</li></b>
                <ol className='sub-list-items'>
                    <li>Charges paid by you are final and non-refundable unless otherwise determined by Veri Doctor.</li>
                    <li>The refund will be made on the same payment method, if applicable.</li>
                    <li>Veri Doctor reserves its right to refund any amounts into the user&apos;s account to be used in other services at its sole discretion.</li>
                    <li>Refunds are not applicable if the User is unsatisfied with the medical service provided.</li>
                    <li>A User will be entitled to a full refund if:
                        <ul>
                            <li>The User canceled the reservation before the appointment time;</li>
                            <li>The Provider canceled, or did not show up to, the appointment for which payment was made by the User;</li>
                        </ul>
                    </li>
                </ol>
                <b><li>User Confidentiality</li></b>
                    <ol className='sub-list-items'>
                        <li>We consider the privacy and confidentiality of our Users’ data a sacred matter. However, we understand the nature of the service you provide and how important you need to identify certain personal information.</li>
                        <li>Therefore, we hereby grant you access to the data deemed important to carry out your services namely the name, telephone number, and e-mail address of the Users. However, the access shall be exercised for the sole purpose of enhancing internal operations and not for promotional purposes.</li>
                        <li>In the event of a breach of the foregoing, you acknowledge that you will be liable to defend, protect, indemnify, and hold harmless Veri Doctor, against any claims, proceedings, or lawsuits arising out of damages, losses, injuries, costs, losses or expenses of whatever nature caused to the Users due to the divulging and disclosure of their personal information by the Provider.</li>                    </ol>
                <b><li>Intellectual Property</li></b>
                    <ol className='sub-list-items'>
                        <li>Veri Doctor respects the intellectual property rights of others and expects its users to do the same. Veri Doctor may remove content that in its sole discretion appears to infringe the intellectual property rights of others. In addition, Veri Doctor will, at its sole discretion, terminate the accounts of users who infringe the intellectual property rights of others. If you believe that a user of the Application or the Services has infringed your copyrights, trademark, or those of others, please notify Veri Doctor by using the info email or by contacting the legal department of Veri Doctor.</li>
                        <li>Veri Doctor will retain ownership of its intellectual property rights and you may not obtain any rights therein, except as expressly outlined in a written approval. You will have no right to use, copy, display, perform, create derivative works from, distribute, transmit, or sublicense any material or content available on the application, than as may be reasonably necessary to use the Services for their intended purposes and except as expressly outlined in these Terms. You may not attempt to reverse engineer any of the technology used to provide the Services. If you become aware of any conduct that violates these Terms, Veri Doctor encourages you to contact us.</li>
                        <li>Our platform may contain links to third-party websites, advertisers, or services that are not owned by Veri Doctor. You acknowledge and understand that such content may be subject to different terms of use and privacy policies than Veri Doctor’s. Therefore, the present Terms do not apply to you when accessing or using third parties’ services. If you access third parties’ websites from our Services, you do so at your liability and you consent to release Veri Doctor from any liability arising out of such use.</li>

                    </ol>
                <b><li>Representations and Warranties</li></b>
                    <p>You represent and warrant to Veri Doctor that:</p>
                    <ol className='sub-list-items'>
                        <li>you have the full power and authority to enter into and perform your obligations under these Terms.</li>
                        <li>your assent to and performance of your obligations under these Terms does not constitute a breach of or conflict with any other lawful obligations whatsoever, agreements, arrangements, any applicable laws, regulations rules; or any court sentences and rulings by which you are bound.</li>
                        <li>these Terms constitute legal, valid, and binding obligations on you, enforceable by its terms and conditions.</li>
                        <li>you will not infringe the copyright, trademark, trade secret, right of publicity, or other intellectual property of any third party while using the Website or the Services, or the right of privacy of your customers/ patients;</li>
                        <li>that you will comply with all applicable laws, rules, and regulations in your use of the Services and the Website, including these Terms,</li>
                        <li>and that you are a duly qualified physician in your field(s) of practice.</li>
                    </ol>
                <b><li>Warranty Disclaimer</li></b>
                    <ol className='sub-list-items'>
                        <li>You agree that your use of the application shall be at your sole risk. To the fullest extent permitted by law, Veri Doctor, its officers, directors, employees, agents, and shareholders disclaim all warranties, express or implied, in connection with the Services and your use thereof. Veri Doctor makes no warranties or representations about the accuracy or completeness of this application&apos;s content or the content of any sites linked to this application and assumes no liability thereon.</li>
                        <li>Veri Doctor does not warrant, endorse, guarantee, or assume any responsibility for any product or service advertised or offered by a third party through the Services or any hyperlinked services featured in any banner or other advertising, and Veri Doctor will not be a party to or in any way be responsible for monitoring any transaction between you and third parties.</li>
                    </ol>
                <b><li>Limitation of Liability</li></b>
                    <ol className='sub-list-items'>
                        <li>You understand that you shall be responsible for offering the User a professional, accurate, and proficient medical treatment generally offered by highly skilled and qualified healthcare providers.</li>
                        <li>Therefore, Veri Doctor will not under any circumstances be responsible for the dissatisfaction of the User with the consultation and examination held with you and his disappointment with his experience with you in general.</li>
                        <li>To the extent permitted by law, in no event shall Veri Doctor, its officers, directors, employees, or agents, be liable to you for any direct, indirect, incidental, special, punitive, or consequential damages whatsoever, arising out of, resulting from or in connection with any (i) errors, mistakes, or inaccuracies of content, (ii) personal injury or damage, of any nature whatsoever, resulting from your access to and use of our Services, (iii) any unauthorized access to or use of our secure servers and/or any and all personal information and/or financial information stored therein, (iv) any interruption or cessation of transmission to or from our Services, (iv) any bugs, viruses, trojan horses, or the like, which may be transmitted to or through our Services by any third party, and/or (v) any errors or omissions in any content or for any loss or damage of any kind incurred as a result of your use of any content posted, emailed, transmitted, or otherwise made available via the Services, whether based on a warranty, contract, tort, or any other legal theory, and whether or not the company has warned about the possibility of such damages. the foregoing limitation of liability shall apply to the fullest extent permitted by law.</li>
                        <li>You specifically acknowledge that Veri Doctor shall not be liable for the defamatory, offensive, or illegal conduct of any third party and that the risk, harm, or damage from the foregoing rests entirely on you.</li>
                        <li>Moreover, Services are controlled and offered by Veri Doctor from its facilities. Veri Doctor makes no representations that the Service is appropriate or available for use in other locations. Those who access or use the Service from other jurisdictions do so at their own volition and are responsible for compliance with their local law.</li>
                    </ol>
                <b><li>Indemnification</li></b>
                    <ol className="sub-list-items">
                        <li>To the extent permitted by applicable law, you agree to defend, indemnify and hold Veri Doctor, its representatives, officers, directors, employees and agents, shareholders, (“Indemnified Parties”) harmless from any damage, loss, cost or expense (including without limitation, attorneys’ fees and costs), incurred in connection with any claim, demand or action, brought or asserted against any of the Indemnified Parties, arising out of, or in connection with, (i) your use of and access to the Service; (ii) your violation of any term of these Terms; (iii) alleging facts or circumstances that would constitute a breach of any provision of these Terms by you, including violations of law or allegations of violation of privacy, publicity, or intellectual property rights related to User Created Content you submit; or Veri Doctor’s created contents; (iv) arising from, related to, or connected with your use of the Website or the Services violating any third party right, including without limitation any copyright, property, or privacy right; (v) any other party’s access and use of the Services with your unique username, password or other appropriate security code</li>
                        <li>If you are obligated to provide indemnification under this provision, Veri Doctor may, in its sole and absolute discretion, control the disposition of any Claim at your sole cost and expense. Without limiting the foregoing, you may not settle, compromise or in any other manner dispose of any Claim without the prior written consent of Veri Doctor.</li>
                        <li>You acknowledge and undertake to defend, protect, indemnify, and hold harmless Veri Doctor, its officers, officials, and employees from all claims, injuries, damages, losses, or suits including attorney fees, arising out of, resulting from, or in connection any fraudulent, deceptive, deceitful, counterfeiting or generally illegal act committed by you for any reason whatsoever.</li>
                        <li>The Provider shall defend, indemnify, and hold Veri Doctor, its officers, officials, and employees harmless from any claims, injuries, damages, losses or suits including attorney fees, arising out of, resulting from or in connection with any act, errors, omissions of the user.</li>
                        <li>Moreover, you acknowledge that you shall be solely liable and fully responsible for the accuracy of the diagnosis or the treatment of the patient you dealt with through Veri Doctor’s Services. Veri Doctor shall not be held accountable under any circumstances to endure any responsibility due to any medical error, malpractice, or gross negligence committed by the physician as Veri Doctor exercises the sole role of the intermediary party between the physician and the patient.</li>
                    </ol>
                <b><li>Force Majeure</li></b>
                    <p>Veri Doctor will not be liable for failing to perform under these Terms by the occurrence of any event beyond its reasonable control, including, without limitation, fire, terrorism, natural disaster, war, boycott, labor disturbance, Internet or communications outage, interruption of service, or failure by a service provider of Veri Doctor to perform its obligations.</p>
                <b><li>Termination</li></b>
                    <ol className="sub-list-item">
                        <li>Veri Doctor will have the right in its sole discretion, for any reason, with no liability towards you or any third party, to terminate your account or your access to the application or Services. Such reasons may include, without limitation: (i) your breach of any part of these Terms, (ii) your violation of the rights of any third party; (iii) the invalidity of your credit card, your exceeding your credit card limit or “chargeback” of a fee or other payment; or (iv) your Provider account becoming inactive for an extended period.</li>
                        <li>Effect of Termination. If your account is terminated, Veri Doctor may, in its sole discretion, delete any websites, files, graphics, or other content or materials relating to your use of the Website or Services on servers owned or operated for Veri Doctor or otherwise in its possession, and Veri Doctor will have no liability to you or any third party for doing so. Following termination, you will not be permitted to use the Website or the Services. If your account or your access to the Website or Services is terminated, Veri Doctor reserves the right to exercise whatever means it deems necessary to prevent unauthorized access to the Website or the Services, including, but not limited to, technological barriers, IP mapping and direct contact with your Internet Service Provider (ISP). If your account is terminated, you must immediately pay Veri Doctor any fees that you owe it. Regardless of whether you have the right to access or use the Website or the Services.</li>
                    </ol>
                <b><li>Miscellaneous</li></b>
                    <ol className="sub-list-items">
                        <li>These Terms contain the entire understanding of you and Veri Doctor regarding the use of the application and supersedes all prior and contemporaneous agreements and understandings between you and Veri Doctor regarding its subject matter. These Terms will be binding upon each party hereto and its successors and permitted assigns. No failure or delay by a party in exercising any right, power, or privilege under these Terms will be deemed as a waiver thereof, nor will any single or partial exercise of any right, power or privilege preclude the other party from further exercise thereof or the exercise of any other right, authority, or privilege under these Terms.</li>
                        <li>You and Veri Doctor are independent contractors, your relationship with Veri Doctor does not constitute in any way an agency, partnership, joint venture; or employee-employer relationship.</li>
                        <li>The invalidity or unenforceability of any provision of these Terms will not affect the validity or enforceability of any other provisions of these Terms, all of which will remain in full force and effect.</li>
                        <li>These Terms and the contract have been drawn in both languages English and Arabic, drawn in two counterparts, an original for each party to act upon it. In the event of conflict or discrepancy between the two languages of the Contract or between the Contract and the Terms, the English version and the Terms shall prevail.</li>
                        <li>Veri Doctor reserves the right to update, change, or amend these Terms at any time, and for any reason by posting the amended version on the application so that the amended Terms apply to all Veri Doctor’s Services, effective immediately after being posted on the application. In other words, the Service offered to you will be governed by the Terms existing on the date of the Service. Your acceptance to the Terms in its amended version, will be deemed by your continuous access and use of the application and the Services contained therein as of the effective date of any such modification.</li>
                    </ol>
                <b><li>Governing Law and Jurisdiction</li></b>
                <p>These Terms shall be governed by and construed following Kenyan laws. Any dispute arising out of or in connection with the interpretation and/ or the execution of this Agreement shall be finally resolved by arbitration before the Nairobi Centre for International Arbitration (the &quot;Centre&quot;) by the Centre&apos;s rules in force at the time of the dispute, the arbitral panel shall be composed of one arbitrator, English shall be the language of proceedings. As an exception to the above, Veri Doctor retains the discretionary right to bring proceedings before a court whose jurisdiction extends over the Provider.</p>
            </ol>
        </div>

       </div>
    )
}